# generated by datamodel-codegen:
#   filename:  defaultSchema.json
#   timestamp: 2026-07-27T12:33:38+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict, Field

from validators.config import ConfigModel

class Info(BaseModel):
    pass


class Analyses(ConfigModel):
    model_config = ConfigDict(
        extra='allow',
    )
    aligner: str | None = Field(
        None,
        description='Name or identifier of the mapping/alignment software/pipeline',
        examples=['bwa-0.7.8'],
    )
    analysisDate: date = Field(
        ...,
        description='Date at which analysis was performed.\n',
        examples=['2021-10-17'],
    )
    biosampleId: str | None = Field(
        None,
        description='Local reference to the `id` of the biosample this analysis is reporting on.',
        examples=['S0001', 'onekgbs-NA07346'],
    )
    id: str = Field(
        ..., description='Analysis id for internal referencing; unique in the dataset.'
    )
    individualId: str | None = Field(
        None,
        description='Local reference to the `id` of the individual this analysis is reporting on.',
        examples=['P0001', 'onekgind-NA07346'],
    )
    info: Info | None = None
    pipelineName: str = Field(
        ...,
        description='Analysis pipeline and version.',
        examples=['Pipeline-panel-0001-v1'],
    )
    pipelineRef: str | None = Field(
        None,
        description='Link to information about or repository of the analysis pipeline.',
        examples=[
            'https://doi.org/10.48511/workflowhub.workflow.111.1',
            'https://doi.org/10.1093/bib/bbad541',
        ],
    )
    runId: str | None = Field(
        None,
        description='Local reference to the associated experimental run.',
        examples=['SRR10903401'],
    )
    variantCaller: str | None = Field(
        None,
        description='Name or identifier of the variant calling software/pipeline',
        examples=['GATK4.0', 'labelSeg'],
    )
