# generated by datamodel-codegen:
#   filename:  defaultSchema.json
#   timestamp: 2026-07-27T12:23:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr
from validators.config import ConfigModel

class Info(BaseModel):
    pass


class CopyChange(Enum):
    efo_0030069 = 'efo:0030069'
    efo_0020073 = 'efo:0020073'
    efo_0030068 = 'efo:0030068'
    efo_0030067 = 'efo:0030067'
    efo_0030064 = 'efo:0030064'
    efo_0030070 = 'efo:0030070'
    efo_0030071 = 'efo:0030071'
    efo_0030072 = 'efo:0030072'


class Number(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Number'] = Field(..., description='MUST be "Number"')
    value: int = Field(..., description='The value represented by Number')


class DefiniteRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['DefiniteRange'] = Field(..., description='MUST be "DefiniteRange"')
    min: float = Field(..., description='The minimum value; inclusive')
    max: float = Field(..., description='The maximum value; inclusive')


class Comparator(Enum):
    field__ = '<='
    field___1 = '>='


class IndefiniteRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['IndefiniteRange'] = Field(
        ..., description='MUST be "IndefiniteRange"'
    )
    value: int = Field(..., description='The bounded value; inclusive')
    comparator: Comparator = Field(
        ...,
        description='MUST be one of "<=" or ">=", indicating which direction the range is indefinite',
    )


class CURIE(RootModel[constr(pattern=r'^\w[^:]*:.+$')]):
    root: constr(pattern=r'^\w[^:]*:.+$') = Field(
        ...,
        description='A [W3C Compact URI](https://www.w3.org/TR/curie/) formatted string. A CURIE string has the structure ``prefix``:``reference``, as defined by the W3C syntax.',
        examples=['ensembl:ENSG00000139618'],
    )


class HumanCytoband(
    RootModel[constr(pattern=r'^cen|[pq](ter|([1-9][0-9]*(\.[1-9][0-9]*)?))$')]
):
    root: constr(pattern=r'^cen|[pq](ter|([1-9][0-9]*(\.[1-9][0-9]*)?))$') = Field(
        ...,
        description='A character string representing cytobands derived from the *International System for Human Cytogenomic Nomenclature* (ISCN) [guidelines](http://doi.org/10.1159/isbn.978-3-318-06861-0).',
        examples=['q22.3'],
    )


class Residue(RootModel[constr(pattern=r'[A-Z*\-]')]):
    root: constr(pattern=r'[A-Z*\-]') = Field(
        ...,
        description='A character representing a specific residue (i.e., molecular species) or groupings of these ("ambiguity codes"), using [one-letter IUPAC abbreviations](https://en.wikipedia.org/wiki/International_Union_of_Pure_and_Applied_Chemistry#Amino_acid_and_nucleotide_base_codes) for nucleic acids and amino acids.',
    )


class Sequence(RootModel[constr(pattern=r'^[A-Z*\-]*$')]):
    root: constr(pattern=r'^[A-Z*\-]*$') = Field(
        ...,
        description='A character string of Residues that represents a biological sequence using the conventional sequence order (5’-to-3’ for nucleic acid sequences, and amino-to-carboxyl for amino acid sequences). IUPAC ambiguity codes are permitted in Sequences.',
    )


class SequenceState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['SequenceState'] = Field(..., description='MUST be "SequenceState"')
    sequence: Sequence = Field(..., description='A string of Residues')


class SimpleInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['SimpleInterval'] = Field(..., description='MUST be "SimpleInterval"')
    start: int = Field(..., description='The start coordinate')
    end: int = Field(..., description='The end coordinate')


class CURIEModel(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: str | None = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CountAdjustedToItem(RootModel[conint(ge=1) | str]):
    root: conint(ge=1) | str


class CountAdjustedTo(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[list[str]]):
    root: list[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        10,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        True,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class SchemasPerEntity(BaseModel):
    entityType: str | None = Field(None, examples=['Individual'])
    schema_: str | None = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        0,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class TestMode(RootModel[bool]):
    root: bool = Field(
        False,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str | None = Field(
        None,
        description='An application specific identifier. RECOMMENDED.',
        examples=['PMID:34054918'],
    )
    notes: str | None = Field(
        None,
        description='An optional text descriptor. Renamed compared to GA4GH Phenopackets v2 `ExternalReference.description`',
        examples=[
            'Signatures of Discriminative Copy Number Aberrations in 31 Cancer Subtypes'
        ],
    )
    reference: str | None = Field(
        None,
        description='A url.',
        examples=['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8155688/'],
    )


class ClinicalRelevance(Enum):
    benign = 'benign'
    likely_benign = 'likely benign'
    uncertain_significance = 'uncertain significance'
    likely_pathogenic = 'likely pathogenic'
    pathogenic = 'pathogenic'


class PopulationFrequency(BaseModel):
    alleleFrequency: float = Field(
        ..., description='Allele frequency between 0 and 1.', examples=[3.186e-05]
    )
    population: str = Field(
        ...,
        description='A name for the population. A population could an ethnic, geographical one or just the members of a study.',
        examples=[
            'East Asian',
            'ICGC Chronic Lymphocytic Leukemia-ES',
            'Men',
            'Children',
        ],
    )


class SoftwareTool(BaseModel):
    toolName: str = Field(
        ...,
        description='Name of the tool.',
        examples=['Ensembl Variant Effect Predictor (VEP)'],
    )
    toolReferences: dict[str, Any] = Field(
        ...,
        description='References to the tool',
        examples=[
            {'bio.toolsId': 'https://bio.tools/vep'},
            {'url': 'https://www.ensembl.org/vep'},
        ],
        min_length=1,
    )
    version: str = Field(..., description='Version used.', examples=['rel 104'])


class Text(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['Text'] = Field(..., description='MUST be "Text"')
    definition: str = Field(
        ...,
        description='A textual representation of variation not representable by other subclasses of Variation.',
    )


class SequenceInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['SequenceInterval'] = Field(
        ..., description='MUST be "SequenceInterval"'
    )
    start: DefiniteRange | IndefiniteRange | Number = Field(
        ...,
        description='The start coordinate or range of the interval. The minimum value of this coordinate or range is 0. MUST represent a coordinate or range less than the value of `end`.',
    )
    end: DefiniteRange | IndefiniteRange | Number = Field(
        ...,
        description='The end coordinate or range of the interval. The minimum value of this coordinate or range is 0. MUST represent a coordinate or range greater than the value of `start`.',
    )


class CytobandInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CytobandInterval'] = Field(
        ..., description='MUST be "CytobandInterval"'
    )
    start: HumanCytoband = Field(
        ...,
        description='The start cytoband region. MUST specify a region nearer the terminal end (telomere) of the chromosome p-arm than `end`.',
    )
    end: HumanCytoband = Field(
        ...,
        description='The end cytoband region. MUST specify a region nearer the terminal end (telomere) of the chromosome q-arm than `start`.',
    )


class LiteralSequenceExpression(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['LiteralSequenceExpression'] = Field(
        ..., description='MUST be "LiteralSequenceExpression"'
    )
    sequence: Sequence = Field(..., description='the literal Sequence expressed')


class Gene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['Gene'] = Field(..., description='MUST be "Gene"')
    gene_id: CURIE = Field(..., description='A CURIE reference to a Gene concept')


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIEModel
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class ListOfSchemas(RootModel[list[SchemasPerEntity]]):
    root: list[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class Pagination(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class FrequencyInPopulations(BaseModel):
    frequencies: list[PopulationFrequency] = Field(..., min_length=1)
    source: str = Field(
        ...,
        description='The study',
        examples=[
            'The Genome Aggregation Database (gnomAD)',
            'The European Genome-phenome Archive (EGA)',
        ],
    )
    sourceReference: str = Field(
        ...,
        description='A reference to further documentation or details.',
        examples=['https://gnomad.broadinstitute.org/', 'https://ega-archive.org/'],
    )
    version: str | None = Field(
        None, description='version of the source data.', examples=['gnomAD v3.1.1']
    )


class GenomicFeature(BaseModel):
    featureClass: OntologyTerm = Field(
        ...,
        description='Ontology term that describes the class of genomic feature affected by the variant. Values from SO (Sequence ontology) are recommended, e.g. `SO:0001623: 5 prime UTR variant`',
        examples=[{'id': 'SO:0001623', 'label': '5 prime UTR variant'}],
    )
    featureID: OntologyTerm | None = Field(
        None,
        description='Where applicable, ID/accession/name of genomic feature related to the `featureClass`, preferably in CURIE format. If the value is a gene id or name, it points to the gene related to the `featureClass`, e.g. `the 5 prime UTR upstream of TP53`',
        examples=[{'id': 'HGNC:11998', 'label': 'TP53'}],
    )


class Identifiers(BaseModel):
    clinvarVariantId: constr(pattern=r'^(clinvar:)?\d+$') | None = Field(
        None,
        description='ClinVar variant id. Other id values used by ClinVar can be added to `variantAlternativeIds`',
        examples=['clinvar:12345', '9325'],
    )
    genomicHGVSId: str | None = Field(
        None, description='HGVSId descriptor.', examples=['NC_000017.11:g.43057063G>A']
    )
    proteinHGVSIds: list[str] | None = Field(
        None,
        description='List of HGVSId descriptor(s) at protein level (for protein-altering variants).',
        examples=[['NP_009225.1:p.Glu1817Ter'], ['LRG 199p1:p.Val25Gly (preferred)']],
    )
    transcriptHGVSIds: list[str] | None = Field(
        None,
        description='List of HGVSId descriptor(s) at transcript level.',
        examples=[['NC 000023.10(NM004006.2):c.357+1G']],
    )
    variantAlternativeIds: list[ExternalReference] | None = Field(
        None,
        description='List of cross-referencing ID(s), for the variant in other databases (e.g. dbSNP, ClinVar, ClinGen, COSMIC), as `externalReferences` with CURIE(s).',
        examples=[
            [
                {
                    'id': 'dbSNP:rs587780345',
                    'notes': 'dbSNP id',
                    'reference': 'https://www.ncbi.nlm.nih.gov/snp/rs587780345',
                },
                {
                    'id': 'ClinGen:CA152954',
                    'notes': 'ClinGen Allele Registry id',
                    'reference': 'https://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA152954',
                },
                {
                    'id': 'UniProtKB:P35557#VAR_003699',
                    'reference': 'https://www.uniprot.org/uniprot/P35557#VAR_003699',
                },
            ],
            [
                {
                    'id': 'OMIM:164757.0001',
                    'reference': 'https://www.omim.org/entry/164757#0001',
                }
            ],
        ],
    )


class MolecularAttributes(BaseModel):
    aminoacidChanges: list[str] | None = Field(
        None,
        description='Lisf of change(s) at aminoacid level for protein affecting variants.',
        examples=[['V304*']],
    )
    geneIds: list[str] | None = Field(
        None,
        description='Symbolic names or identifiers used for a gene',
        examples=[['ACE2'], ['BRCA1', 'ENSG00000012048']],
    )
    genomicFeatures: list[GenomicFeature] | None = Field(
        None, description='List of Genomic feature(s) affected by the variant.'
    )
    molecularEffects: list[OntologyTerm] | None = Field(
        None,
        description='Ontology term that includes describes the class of molecular consequence generated by the variant. Values from SO (Sequence Ontology) are recommended, e.g.  `SO:0001583: missense variant`.',
        examples=[
            {'id': 'SO:0002322', 'label': 'stop gained NMD escaping'},
            {'id': 'SO:0001583', 'label': 'missense variant'},
        ],
    )


class PhenoClinicEffect(BaseModel):
    annotatedWith: SoftwareTool | None = None
    category: OntologyTerm | None = Field(
        None,
        description='Ontology term for the type of disease, condition, phenotypic measurement, etc.',
        examples=[
            {'id': 'MONDO:0000001', 'label': 'disease or disorder'},
            {'id': 'HP:0000118', 'label': 'phenotypic abnormality'},
        ],
    )
    clinicalRelevance: ClinicalRelevance | None = Field(
        None,
        description='Indication of the clinical relevance of the variant Recommended: A value from the five-tiered classification from the American College of Medical Genetics (ACMG) designed to describe the likelihood that a genomic sequence variant is causative of an inherited disease. (NCIT:C168798).',
        examples=['pathogenic'],
    )
    conditionId: str = Field(
        ...,
        description='Internal identifier of the phenotype or clinical effect.',
        examples=['disease1', 'phen2234'],
    )
    effect: OntologyTerm = Field(
        ...,
        description='Ontology term for the phenotypic or clinical effect',
        examples=[
            {
                'id': 'MONDO:0003582',
                'label': 'hereditary breast ovarian cancer syndrome',
            },
            {'id': 'HP:0000256', 'label': 'macrocephaly'},
        ],
    )
    evidenceType: OntologyTerm | None = Field(
        None,
        description='Ontology term for the type of evidence supporting variant-disease association Recommended: values from the Evidence & Conclusion Ontology (ECO)',
        examples=[
            {'id': 'ECO:0000361', 'label': 'inferential evidence'},
            {'id': 'ECO:0000006', 'label': 'experimental evidence'},
        ],
    )


class VariantLevelData(BaseModel):
    clinicalInterpretations: list[PhenoClinicEffect] | None = None
    phenotypicEffects: list[PhenoClinicEffect] | None = None


class ChromosomeLocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Location Id. MUST be unique within document.'
    )
    type: Literal['ChromosomeLocation'] = Field(
        ..., description='MUST be "ChromosomeLocation"'
    )
    species_id: CURIE = Field(
        ...,
        description='CURIE representing a species from the [NCBI species taxonomy](https://registry.identifiers.org/registry/taxonomy). Default: "taxonomy:9606" (human)',
    )
    chr: str = Field(
        ...,
        description='The symbolic chromosome name. For humans, For humans, chromosome names MUST be one of 1..22, X, Y (case-sensitive)',
    )
    interval: CytobandInterval = Field(
        ..., description='The chromosome region defined by a CytobandInterval'
    )


class SequenceLocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Location Id. MUST be unique within document.'
    )
    type: Literal['SequenceLocation'] = Field(
        ..., description='MUST be "SequenceLocation"'
    )
    sequence_id: CURIE = Field(
        ..., description='A VRS Computed Identifier for the reference Sequence.'
    )
    interval: SequenceInterval | SimpleInterval = Field(
        ..., description='Reference sequence region defined by a SequenceInterval.'
    )


class DerivedSequenceExpression(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['DerivedSequenceExpression'] = Field(
        ..., description='MUST be "DerivedSequenceExpression"'
    )
    location: SequenceLocation = Field(
        ..., description='The location from which the approximate sequence is derived'
    )
    reverse_complement: bool = Field(
        ...,
        description='A flag indicating if the expressed sequence is the reverse complement of the sequence referred to by `location`',
    )


class RepeatedSequenceExpression(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['RepeatedSequenceExpression'] = Field(
        ..., description='MUST be "RepeatedSequenceExpression"'
    )
    seq_expr: DerivedSequenceExpression | LiteralSequenceExpression = Field(
        ..., description='An expression of the repeating subsequence'
    )
    count: DefiniteRange | IndefiniteRange | Number = Field(
        ..., description='The count of repeated units, as an integer or inclusive range'
    )


class ComposedSequenceExpression(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ComposedSequenceExpression'] = Field(
        'ComposedSequenceExpression', description='MUST be "ComposedSequenceExpression"'
    )
    components: list[
        DerivedSequenceExpression
        | LiteralSequenceExpression
        | RepeatedSequenceExpression
    ] = Field(
        ...,
        description='An ordered list of SequenceExpression components   comprising the expression.',
        min_length=2,
    )


class Feature(RootModel[Gene]):
    root: Gene = Field(
        ...,
        description='A named entity that can be mapped to a Location. Genes, protein domains, exons, and chromosomes are some examples of common biological entities that may be Features.',
        discriminator='type',
    )


class CaseLevelVariant(BaseModel):
    alleleOrigin: OntologyTerm | None = Field(
        None,
        description='Ontology value for allele origin of variant in sample from the Variant Origin (SO:0001762). Categories are `somatic variant`, `germline variant`, `maternal variant`, `paternal variant`, `de novo variant`, `pedigree specific variant`, `population specific variant`. Corresponds to Variant Inheritance in FHIR.',
        examples=[
            {'id': 'SO:0001777', 'label': 'somatic variant'},
            {'id': 'SO:0001778', 'label': 'germline variant'},
            {'id': 'SO:0001775', 'label': 'maternal variant'},
            {'id': 'SO:0001776', 'label': 'paternal variant'},
            {'id': 'SO:0001781', 'label': 'de novo variant'},
            {'id': 'SO:0001779', 'label': 'pedigree specific variant'},
            {'id': 'SO:0001780', 'label': 'population specific variant'},
        ],
    )
    analysisId: str | None = Field(
        None,
        description='Reference to the bioinformatics analysis ID (`analysis.id`)',
        examples=['pgxcs-kftvldsu'],
    )
    biosampleId: str = Field(
        ...,
        description='Reference to biosample ID (`biosample.id`)',
        examples=['bs001104'],
    )
    clinicalInterpretations: list[PhenoClinicEffect] | None = None
    id: str | None = Field(
        None,
        description='Internal id of this case level *instance* of the variant. This is an optional housekeeping parameter and should not be confused with the identifier of the variant (`variantInternalId`).',
        examples=['id0001-var101101118'],
    )
    individualId: str | None = Field(
        None,
        description='Reference to individual ID (`individual.id`)',
        examples=['ind0001'],
    )
    phenotypicEffects: list[PhenoClinicEffect] | None = None
    runId: str | None = Field(
        None,
        description='Reference to the experimental run ID (`run.id`)',
        examples=['SRR10903401'],
    )
    zygosity: OntologyTerm | None = Field(
        None,
        description='Ontology term for zygosity in which variant is present in the sample from the Zygosity Ontology (GENO:0000391) , e.g `heterozygous` (GENO:0000135)',
        examples=[
            {'id': 'GENO:0000135', 'label': 'heterozygous'},
            {'id': 'GENO:0000136', 'label': 'homozygous'},
            {'id': 'GENO:0000604', 'label': 'hemizygous X-linked'},
        ],
    )


class Handover(BaseModel):
    handoverType: HandoverType
    note: str | None = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Allele(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['Allele'] = Field(..., description='MUST be "Allele"')
    location: CURIE | ChromosomeLocation | SequenceLocation = Field(
        ..., description='Where Allele is located'
    )
    state: (
        ComposedSequenceExpression
        | DerivedSequenceExpression
        | LiteralSequenceExpression
        | RepeatedSequenceExpression
        | SequenceState
    ) = Field(
        ...,
        description='An expression of the sequence state',
        json_schema_extra={'deprecated': [{'$ref': '#/definitions/SequenceState'}]},
    )


class Haplotype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['Haplotype'] = Field(..., description='MUST be "Haplotype"')
    members: list[Allele | CURIE] = Field(
        ...,
        description='List of Alleles, or references to Alleles, that comprise this Haplotype.',
        min_length=2,
    )


class CopyNumberCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['CopyNumberCount'] = Field(
        ..., description='MUST be "CopyNumberCount"'
    )
    subject: CURIE | ChromosomeLocation | Gene | SequenceLocation = Field(
        ...,
        description='A location for which the number of systemic copies is described.',
    )
    copies: DefiniteRange | IndefiniteRange | Number = Field(
        ..., description='The integral number of copies of the subject in a system'
    )


class CopyNumberChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['CopyNumberChange'] = Field(
        ..., description='MUST be "CopyNumberChange"'
    )
    subject: CURIE | ChromosomeLocation | Gene | SequenceLocation = Field(
        ...,
        description='A location for which the number of systemic copies is described.',
    )
    copy_change: CopyChange = Field(
        ...,
        description='MUST be one of "efo:0030069" (complete genomic loss), "efo:0020073" (high-level loss),  "efo:0030068" (low-level loss), "efo:0030067" (loss), "efo:0030064" (regional base ploidy),  "efo:0030070" (gain), "efo:0030071" (low-level gain), "efo:0030072" (high-level gain).',
    )


class Location(RootModel[ChromosomeLocation | SequenceLocation]):
    root: ChromosomeLocation | SequenceLocation = Field(
        ...,
        description='A contiguous segment of a biological sequence.',
        discriminator='type',
    )


class SequenceExpression(
    RootModel[
        ComposedSequenceExpression
        | DerivedSequenceExpression
        | LiteralSequenceExpression
        | RepeatedSequenceExpression
    ]
):
    root: (
        ComposedSequenceExpression
        | DerivedSequenceExpression
        | LiteralSequenceExpression
        | RepeatedSequenceExpression
    ) = Field(
        ..., description='An expression describing a Sequence.', discriminator='type'
    )


class GenotypeMember(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['GenotypeMember'] = Field(
        ..., description='MUST be "GenotypeMember".'
    )
    count: DefiniteRange | IndefiniteRange | Number = Field(
        ..., description='The number of copies of the `variation` at a Genotype locus.'
    )
    variation: Allele | Haplotype = Field(
        ..., description='A MolecularVariation at a Genotype locus.'
    )


class LegacyVariation(BaseModel):
    alternateBases: constr(pattern=r'^([ACGTUNRYSWKMBDHV\-\.]*)$') = Field(
        ...,
        description='Alternate bases for this variant (starting from `start`). * Accepted values: IUPAC codes for nucleotides (e.g. `https://www.bioinformatics.org/sms/iupac.html`). * N is a wildcard, that denotes the position of any base, and can be used as\n  a standalone base of any type or within a partially known sequence.\n* an *empty value* is used in the case of deletions with the maximally\n  trimmed, deleted sequence being indicated in `ReferenceBases`',
        examples=['T', 'G', 'N', 'AG', ''],
    )
    location: Location
    referenceBases: constr(pattern=r'^([ACGTUNRYSWKMBDHV\-\.]*)$') | None = Field(
        None,
        description='Reference bases for this variant (starting from `start`). * Accepted values: IUPAC codes for nucleotides (e.g. `https://www.bioinformatics.org/sms/iupac.html`). * N is a wildcard, that denotes the position of any base, and can be used\n  as a standalone base of any type or within a partially known sequence.\n* an *empty value* is used in the case of insertions with the maximally\n  trimmed, inserted sequence being indicated in `AlternateBases`.',
        examples=['A', 'T', 'N', '', 'ACG'],
    )
    variantType: str = Field(
        ...,
        description='The `variantType` declares the nature of the variation in relation to a reference. In a response, it is used to describe the variation. Examples here are e.g. structural variants such as `DUP` (increased allelic count of material from the genomic region  between `start` and `end` positions without assumption about the placement of the additional sequence) or `DEL` (deletion of sequence following `start`). Either `alternateBases` or `variantType` is required in representing a `LegacyVariation`.',
        examples=['SNP', 'DEL', 'DUP', 'BND'],
    )


class MolecularVariation(RootModel[Allele | Haplotype]):
    root: Allele | Haplotype = Field(
        ..., description='A variation on a contiguous molecule.', discriminator='type'
    )


class Genotype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['Genotype'] = Field(..., description='MUST be "Genotype"')
    members: list[GenotypeMember] = Field(
        ...,
        description='Each GenotypeMember in `members` describes a MolecularVariation and the count of that variation at the locus.',
        min_length=1,
    )
    count: DefiniteRange | IndefiniteRange | Number = Field(
        ...,
        description='The total number of copies of all MolecularVariation at this locus, MUST be greater than or equal to the sum of GenotypeMember copy counts and MUST be greater than or equal to 1. If greater than the total of GenotypeMember counts, this field describes  additional MolecularVariation that exist but are not  explicitly described.',
    )


class SystemicVariation(RootModel[CopyNumberChange | CopyNumberCount | Genotype]):
    root: CopyNumberChange | CopyNumberCount | Genotype = Field(
        ...,
        description='A Variation of multiple molecules in the context of a system, e.g. a genome, sample, or homologous chromosomes.',
        discriminator='type',
    )


class VariationSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_id: CURIE | None = Field(
        None, alias='_id', description='Variation Id. MUST be unique within document.'
    )
    type: Literal['VariationSet'] = Field(..., description='MUST be "VariationSet"')
    members: list[
        Allele
        | CURIE
        | CopyNumberChange
        | CopyNumberCount
        | Genotype
        | Haplotype
        | Text
        | VariationSet
    ] = Field(
        ...,
        description='List of Variation objects or identifiers. Attribute is required, but MAY be empty.',
    )


class Genomicvariations(ConfigModel):
    model_config = ConfigDict(
        extra='allow',
    )
    caseLevelData: list[CaseLevelVariant] | None = Field(
        None,
        description='caseLevelData reports about the variation instances observed in individual analyses.',
    )
    frequencyInPopulations: list[FrequencyInPopulations] | None = None
    identifiers: Identifiers | None = None
    info: Info | None = None
    molecularAttributes: MolecularAttributes | None = None
    variantInternalId: str = Field(
        ...,
        description='Reference to the **internal** variant ID. This represents the primary key/identifier of that variant **inside** a given Beacon instance. Different Beacon instances may use identical id values, referring to unrelated variants. Public identifiers such as the GA4GH Variant Representation Id (VRSid) MUST be returned in the `identifiers` section. A Beacon instance can, of course, use the VRSid as their own internal id but still MUST represent this then in the `identifiers` section.',
        examples=['var00001', 'v110112'],
    )
    variantLevelData: VariantLevelData | None = None
    variation: MolecularVariation | SystemicVariation | LegacyVariation


class Variation(
    RootModel[
        Allele
        | CopyNumberChange
        | CopyNumberCount
        | Genotype
        | Haplotype
        | Text
        | VariationSet
    ]
):
    root: (
        Allele
        | CopyNumberChange
        | CopyNumberCount
        | Genotype
        | Haplotype
        | Text
        | VariationSet
    ) = Field(
        ...,
        description='A representation of the state of one or more biomolecules.',
        discriminator='type',
    )


class UtilityVariation(RootModel[Text | VariationSet]):
    root: Text | VariationSet = Field(
        ...,
        description='A collection of Variation subclasses that cannot be constrained to a specific class of biological variation, but are necessary for some applications of VRS.',
        discriminator='type',
    )


VariationSet.model_rebuild()
