# generated by datamodel-codegen:
#   filename:  defaultSchema.json
#   timestamp: 2026-07-27T12:24:46+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr
)

from config import ConfigModel





class CURIE(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: str | None = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CountAdjustedToItem(RootModel[conint(ge=1) | str]):
    root: conint(ge=1) | str


class CountAdjustedTo(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[list[str]]):
    root: list[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        10,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        True,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class SchemasPerEntity(BaseModel):
    entityType: str | None = Field(None, examples=['Individual'])
    schema_: str | None = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        0,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class TestMode(RootModel[bool]):
    root: bool = Field(
        False,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class Info(BaseModel):
    pass


class CountAdjustedTo1(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class ListOfSchemas(RootModel[list[SchemasPerEntity]]):
    root: list[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class Pagination1(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class KaryotypicSex(Enum):
    UNKNOWN_KARYOTYPE = 'UNKNOWN_KARYOTYPE'
    XX = 'XX'
    XY = 'XY'
    XO = 'XO'
    XXY = 'XXY'
    XXX = 'XXX'
    XXYY = 'XXYY'
    XXXY = 'XXXY'
    XXXX = 'XXXX'
    XYY = 'XYY'
    OTHER_KARYOTYPE = 'OTHER_KARYOTYPE'


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description='Time in date-time ISO8601 string format.',
        examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00'],
    )


class Age(BaseModel):
    iso8601duration: str = Field(
        ...,
        description='Represents age as a ISO8601 duration (e.g., P40Y10M05D).',
        examples=['P32Y6M1D'],
    )


class AgeRange(BaseModel):
    end: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P59Y).'
    )
    start: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P18Y).'
    )


class GestationalAge(BaseModel):
    days: int | None = Field(
        None,
        description='Days beyond the completed weeks, if available.',
        examples=[2, 4],
    )
    weeks: int = Field(
        ...,
        description='Completed weeks of gestation according to the above definition.',
        examples=[4, 33],
    )


class TimeInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Timestamp = Field(..., examples=['2022-03-10T15:25:07Z'])
    start: Timestamp = Field(
        ..., examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00']
    )


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str | None = Field(
        None,
        description='An application specific identifier. RECOMMENDED.',
        examples=['PMID:34054918'],
    )
    notes: str | None = Field(
        None,
        description='An optional text descriptor. Renamed compared to GA4GH Phenopackets v2 `ExternalReference.description`',
        examples=[
            'Signatures of Discriminative Copy Number Aberrations in 31 Cancer Subtypes'
        ],
    )
    reference: str | None = Field(
        None,
        description='A url.',
        examples=['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8155688/'],
    )


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIE
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class Pagination(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class Handover(BaseModel):
    handoverType: HandoverType
    note: str | None = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers1(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Ethnicity(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Ethnic background of the individual. Recommended is the use of a value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ]',
        examples=[
            {'id': 'NCIT:C42331', 'label': 'African'},
            {'id': 'NCIT:C41260', 'label': 'Asian'},
            {'id': 'NCIT:C126535', 'label': 'Australian'},
            {'id': 'NCIT:C43851', 'label': 'European'},
            {'id': 'NCIT:C77812', 'label': 'North American'},
            {'id': 'NCIT:C126531', 'label': 'Latin American'},
            {'id': 'NCIT:C104495', 'label': 'Other race'},
        ],
    )


class GeographicLocation(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Country or region of origin of the individual (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America).',
        examples=[
            {'id': 'GAZ:00002955', 'label': 'Slovenia'},
            {'id': 'GAZ:00002459', 'label': 'United States of America'},
            {'id': 'GAZ:00316959', 'label': 'Municipality of El Masnou'},
            {'id': 'GAZ:00000460', 'label': 'Eurasia'},
        ],
    )


class SeverityLevel(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Severity as applicable to phenotype or disease observed. Recommended are values from Human Phenotype Ontology (HP:0012824), e.g `mild`. The intensity or degree of a manifestation. Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012829', 'label': 'Profound'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
            {'id': 'HP:0012825', 'label': 'Mild'},
            {'id': 'HP:0012827', 'label': 'Borderline'},
        ],
    )


class Sex(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Sex of the individual. Recommended values from NCIT General Qualifier (NCIT:C27993): "unknown" (not assessed or not available) - NCIT:C17998; "female" - NCIT:C16576;  "male" - NCIT:C20197',
        examples=[
            {'id': 'NCIT:C16576', 'label': 'female'},
            {'id': 'NCIT:C20197', 'label': 'male'},
            {'id': 'NCIT:C1799', 'label': 'unknown'},
        ],
    )


class TimeElement(
    RootModel[Age | AgeRange | GestationalAge | Timestamp | TimeInterval | OntologyTerm]
):
    root: Age | AgeRange | GestationalAge | Timestamp | TimeInterval | OntologyTerm = (
        Field(
            ...,
            description='Definition of a wrapper for various time descriptors. This follows the\nPhenopackets structure https://github.com/phenopackets/phenopacket-schema/blob/v2/docs/time-element.rst',
            title='TimeElement',
        )
    )


class Procedure(BaseModel):
    ageAtProcedure: TimeElement | None = Field(
        None, description='Compares to Phenopackets v2 `Procedure.performed`'
    )
    bodySite: OntologyTerm | None = Field(
        None,
        description='Specific body site where the procedure was performed. Recommended valuee from Uber-anatomy ontology (UBERON)',
        examples=[
            {'id': 'UBERON:0003403', 'label': 'Skin of forearm'},
            {'id': 'UBERON:0003214', 'label': 'mammary gland alveolus'},
        ],
    )
    dateOfProcedure: date_aliased | None = Field(
        None,
        description='Date of procedure, in ISO8601 format',
        examples=['2010-07-10'],
    )
    procedureCode: OntologyTerm = Field(
        ...,
        description="Clinical procedure performed with recommended values from Medical Action Ontology (MAXO) 'Medical action' term tree (MAXO:0000001). Compares to Phenopackets v2 `Procedure.code`",
        examples=[
            {'id': 'MAXO:0001175', 'label': 'liver transplantation'},
            {'id': 'MAXO:0000136', 'label': 'high-resolution microendoscopy'},
            {'id': 'OBI:0002654', 'label': 'needle biopsy'},
        ],
    )


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    evidenceCode: OntologyTerm = Field(
        ...,
        description='An ontology class that represents the evidence type',
        examples=[
            {
                'id': 'ECO:0006017',
                'label': 'author statement from published clinical study used in manual assertion',
            }
        ],
    )
    reference: ExternalReference | None = Field(
        None,
        description='Representation of the source of the evidence',
        examples=[
            {
                'id': 'PMID:30962759',
                'label': 'Recurrent Erythema Nodosum in a Child with a SHOC2 Gene Mutation',
            }
        ],
    )


class ListOfHandovers(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Unit(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='The kind of unit. Recommended from NCIT Unit of Category ontology term (NCIT:C42568) descendants',
        examples=[
            {'id': 'NCIT:C70575', 'label': 'Roentgen'},
            {'id': 'NCIT:C28252', 'label': 'Kilogram'},
            {'id': 'NCIT:C28253', 'label': 'Milligram'},
        ],
    )


class PhenotypicFeature(BaseModel):
    evidence: Evidence | None = Field(
        None,
        description='The evidence for an assertion of the observation of a type. RECOMMENDED.',
    )
    excluded: bool | None = Field(
        False,
        description='Flag to indicate whether the phenotypic feature was observed or not. Default is ‘false’, in other words the phenotype was observed. Therefore it is only used in cases where the phenotype was looked for but found to be absent. More formally, this modifier indicates the logical negation of the OntologyClass used in the `featureType` field. CAUTION: It is imperative to check this field for correct interpretation of the phenotype! Source: Phenopackets v2',
    )
    featureType: OntologyTerm = Field(
        ...,
        description='Term denoting the phenotypic feature, preferably using a value from Human Phenotype Ontology (HPO)',
        examples=[
            {'id': 'HP:0000002', 'label': 'Abnormality of body height'},
            {'id': 'HP:0002006', 'label': 'Facial cleft'},
            {'id': 'HP:0012469', 'label': 'Infantile spasms'},
        ],
    )
    modifiers: list[OntologyTerm] | None = Field(
        None,
        description='This subontology is designed to provide terms to characterize and specify the phenotypic abnormalities defined in the Phenotypic abnormality subontology, with respect to severity, laterality, age of onset, and other aspects. Example use here would be one or more terms from HPO Clinical Modifier (HP:0012823). Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0032500', 'label': 'Exacerbated by tobacco use'},
            {'id': 'HP:4000053', 'label': 'Displaced fracture'},
        ],
    )
    notes: str | None = Field(
        None,
        description='Unstructured text to describe additional properties of this phenotypic feature.',
        examples=['Some free text'],
    )
    onset: TimeElement | None = Field(
        None, description='Age or time at which the feature was first observed.'
    )
    resolution: TimeElement | None = Field(
        None, description='Age or time at which the feature resolved or abated.'
    )
    severity: SeverityLevel | None = Field(
        None,
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
        ],
    )


class ReferenceRange(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    high: float = Field(..., description='Upper range end of normal', examples=[135])
    low: float = Field(..., description='Lower range end of normal', examples=[85])
    unit: Unit = Field(
        ...,
        description='The kind of unit.',
        examples=[{'id': 'NCIT:C49670', 'label': 'Millimeter of Mercury'}],
    )


class Quantity(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    referenceRange: ReferenceRange | None = Field(
        None, description='The normal range for the value', examples=[{}]
    )
    unit: Unit
    value: float = Field(..., description='The value of the quantity in the units')


class TypedQuantity(BaseModel):
    quantity: Quantity = Field(
        ...,
        description='Quantity denoting the outcome of the measurement',
        examples=[
            {
                'unit': {'id': 'NCIT:C49670', 'label': 'Millimeter of Mercury'},
                'value': 110,
            }
        ],
    )
    quantityType: OntologyTerm = Field(
        ...,
        description='OntologyClass to describe the type of the measurement. Renamed compared to GA4GH Phenopackets v2 `ComplexValue.TypedQuantity.type`',
        examples=[{'id': 'NCIT:C25298', 'label': 'Systolic Blood Pressure'}],
    )


class Value(RootModel[Quantity | OntologyTerm]):
    root: Quantity | OntologyTerm = Field(
        ...,
        description='Definition of a value class. Provenance: GA4GH Phenopackets v2 `Value`',
        title='Value',
    )


class ComplexValue(BaseModel):
    typedQuantities: list[TypedQuantity] = Field(
        ...,
        description='List of quantities required to fully describe the complex value',
    )


class Measurement(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    assayCode: OntologyTerm = Field(
        ...,
        description='Class that describes the assay used to produce the measurement. Renamed compared to GA4GH Phenopackets v2 `Measurement.assay`',
        examples=[{'id': 'LOINC:26515-7', 'label': 'Platelets [#/volume] in Blood'}],
    )
    date: date_aliased | None = Field(
        None,
        description='Date of measurement. Addition compared to Phenopackets model.',
    )
    measurementValue: Value | ComplexValue = Field(
        ..., description='The result of the measurement'
    )
    notes: str | None = Field(
        None,
        description='Unstructured text to describe this measurement. Addition compared to Phenopackets model.',
        examples=['Some free text'],
    )
    observationMoment: TimeElement | None = Field(
        None,
        description='Moment in time at which measurement was performed. RECOMMENDED. Renamed compared to GA4GH Phenopackets v2 `Measurement.time_observed`',
        examples=[{'age': {'iso8601duration': 'P53Y8M'}}],
    )
    procedure: Procedure | None = Field(
        None,
        description='Clinical procedure performed to acquire the sample used for the measurement',
        examples=[
            {'code': {'id': 'NCIT:C5189', 'label': 'Radical Cystoprostatectomy'}}
        ],
    )


class Biosamples(ConfigModel):
    model_config = ConfigDict(
        extra='allow',
    )
    biosampleStatus: OntologyTerm = Field(
        ...,
        description='Ontology value from Experimental Factor Ontology (EFO) Material Entity term (BFO:0000040). Classification of the sample in abnormal sample (EFO:0009655) or reference sample (EFO:0009654).',
        examples=[
            {'id': 'EFO:0009654', 'label': 'reference sample'},
            {'id': 'EFO:0009655', 'label': 'abnormal sample'},
            {'id': 'EFO:0009656', 'label': 'neoplastic sample'},
            {'id': 'EFO:0010941', 'label': 'metastasis sample'},
            {'id': 'EFO:0010942', 'label': 'primary tumor sample'},
            {'id': 'EFO:0010943', 'label': 'recurrent tumor sample'},
        ],
    )
    collectionDate: date_aliased | None = Field(
        None,
        description='Date of biosample collection in ISO8601 format.',
        examples=['2021-04-23'],
    )
    collectionMoment: str | None = Field(
        None,
        description="Individual's or cell cullture age at the time of sample collection in the ISO8601 duration format `P[n]Y[n]M[n]DT[n]H[n]M[n]S`.",
        examples=['P32Y6M1D', 'P7D'],
    )
    diagnosticMarkers: list[OntologyTerm] | None = Field(
        None, description='Clinically relevant biomarkers. RECOMMENDED.'
    )
    histologicalDiagnosis: OntologyTerm | None = Field(
        None,
        description='Disease diagnosis that was inferred from the histological examination. RECOMMENDED.',
        examples=[{'id': 'NCIT:C3778', 'label': 'Serous Cystadenocarcinoma'}],
    )
    id: str = Field(
        ...,
        description='Biosample identifier (external accession or internal ID).',
        examples=['S0001'],
    )
    individualId: str | None = Field(
        None,
        description='Reference to the individual from which that sample was obtained.',
        examples=['P0001'],
    )
    info: Info | None = None
    measurements: list[Measurement] | None = Field(
        None, description='List of measurements of the sample.'
    )
    notes: str | None = Field(
        None,
        description='Any relevant info about the biosample that does not fit into any other field in the schema.',
        examples=['Some free text'],
    )
    obtentionProcedure: Procedure | None = Field(
        None,
        description='Ontology value from NCIT Intervention or Procedure ontology term (NCIT:C25218) describing the procedure for sample obtention, e.g. NCIT:C15189 (biopsy).',
        examples=[
            {'code': {'id': 'NCIT:C15189', 'label': 'biopsy'}},
            {'code': {'id': 'NCIT:C157179', 'label': 'FGFR1 Mutation Analysis'}},
        ],
    )
    pathologicalStage: OntologyTerm | None = Field(
        None,
        description='Pathological stage, if applicable, preferably as subclass of NCIT:C28108 - Disease Stage Qualifier. RECOMMENDED.',
        examples=[{'id': 'NCIT:C27977', 'label': 'Stage IIIA'}],
    )
    pathologicalTnmFinding: list[OntologyTerm] | None = Field(
        None,
        description='Pathological TNM findings, if applicable, preferably as subclass of NCIT:C48698 - Cancer TNM Finding Category (NCIT:C48698). RECOMMENDED.',
        examples=[
            {'id': 'NCIT:C48725', 'label': 'T2a Stage Finding'},
            {'id': 'NCIT:C48709', 'label': 'N1c Stage Finding'},
            {'id': 'NCIT:C48699', 'label': 'M0 Stage Finding'},
        ],
    )
    phenotypicFeatures: list[PhenotypicFeature] | None = Field(
        None, description='List of phenotypic abnormalities of the sample. RECOMMENDED.'
    )
    sampleOriginDetail: OntologyTerm | None = Field(
        None,
        description="Tissue from which the sample was taken or sample origin matching the category set in 'sampleOriginType'. Value from Uber-anatomy ontology (UBERON) or BRENDA tissue / enzyme source (BTO), Ontology for Biomedical Investigations (OBI) or Cell Line Ontology (CLO), e.g. 'cerebellar vermis' (UBERON:0004720), 'HEK-293T cell' (BTO:0002181), 'nasopharyngeal swab specimen' (OBI:0002606), 'cerebrospinal fluid specimen' (OBI:0002502).",
        examples=[
            {'id': 'UBERON:0000474', 'label': 'female reproductive system'},
            {'id': 'BTO:0002181', 'label': 'HEK-293T cell'},
            {'id': 'OBI:0002606', 'label': 'nasopharyngeal swab specimen'},
        ],
    )
    sampleOriginType: OntologyTerm = Field(
        ...,
        description="Category of sample origin. Value from Ontology for Biomedical Investigations (OBI) material entity (BFO:0000040) ontology, e.g. 'specimen from organism' (OBI:0001479),'xenograft' (OBI:0100058), 'cell culture' (OBI:0001876)",
        examples=[
            {'id': 'OBI:0001479', 'label': 'specimen from organism'},
            {'id': 'OBI:0001876', 'label': 'cell culture'},
            {'id': 'OBI:0100058', 'label': 'xenograft'},
        ],
    )
    sampleProcessing: OntologyTerm | None = Field(
        None,
        description='Status of how the specimen was processed,e.g. a child term of EFO:0009091.',
        examples=[{'id': 'EFO:0009129', 'label': 'mechanical dissociation'}],
    )
    sampleStorage: OntologyTerm | None = Field(
        None, description='Status of how the specimen was stored.', examples=[{}]
    )
    tumorGrade: OntologyTerm | None = Field(
        None,
        description='Term representing the tumor grade. Child term of NCIT:C28076 (Disease Grade Qualifier) or equivalent.',
        examples=[{'id': 'NCIT:C28080', 'label': 'Grade 3a'}],
    )
    tumorProgression: OntologyTerm | None = Field(
        None,
        description='Tumor progression category indicating primary, metastatic or recurrent progression. Ontology value from Neoplasm by Special Category ontology (NCIT:C7062), e.g. NCIT:C84509 (Primary Malignant Neoplasm).',
        examples=[
            {'id': 'NCIT:C84509', 'label': 'Primary Malignant Neoplasm'},
            {'id': 'NCIT:C4813', 'label': 'Recurrent Malignant Neoplasm'},
        ],
    )
