# generated by datamodel-codegen:
#   filename:  defaultSchema.json
#   timestamp: 2026-07-27T12:23:16+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Age(BaseModel):
    iso8601duration: str = Field(
        ...,
        description='Represents age as a ISO8601 duration (e.g., P40Y10M05D).',
        examples=['P32Y6M1D'],
    )


class AgeRange(BaseModel):
    end: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P59Y).'
    )
    start: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P18Y).'
    )


class GestationalAge(BaseModel):
    days: int | None = Field(
        None,
        description='Days beyond the completed weeks, if available.',
        examples=[2, 4],
    )
    weeks: int = Field(
        ...,
        description='Completed weeks of gestation according to the above definition.',
        examples=[4, 33],
    )


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description='Time in date-time ISO8601 string format.',
        examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00'],
    )


class CURIE(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: str | None = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CountAdjustedToItem(RootModel[conint(ge=1) | str]):
    root: conint(ge=1) | str


class CountAdjustedTo(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[list[str]]):
    root: list[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        10,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class SchemasPerEntity(BaseModel):
    entityType: str | None = Field(None, examples=['Individual'])
    schema_: str | None = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class ListOfSchemas(RootModel[list[SchemasPerEntity]]):
    root: list[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        True,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        0,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class Pagination(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class TestMode(RootModel[bool]):
    root: bool = Field(
        False,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class KaryotypicSex(Enum):
    UNKNOWN_KARYOTYPE = 'UNKNOWN_KARYOTYPE'
    XX = 'XX'
    XY = 'XY'
    XO = 'XO'
    XXY = 'XXY'
    XXX = 'XXX'
    XXYY = 'XXYY'
    XXXY = 'XXXY'
    XXXX = 'XXXX'
    XYY = 'XYY'
    OTHER_KARYOTYPE = 'OTHER_KARYOTYPE'


class TimeInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Timestamp = Field(..., examples=['2022-03-10T15:25:07Z'])
    start: Timestamp = Field(
        ..., examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00']
    )


class CountAdjustedTo1(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class Info(BaseModel):
    pass


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str | None = Field(
        None,
        description='An application specific identifier. RECOMMENDED.',
        examples=['PMID:34054918'],
    )
    notes: str | None = Field(
        None,
        description='An optional text descriptor. Renamed compared to GA4GH Phenopackets v2 `ExternalReference.description`',
        examples=[
            'Signatures of Discriminative Copy Number Aberrations in 31 Cancer Subtypes'
        ],
    )
    reference: str | None = Field(
        None,
        description='A url.',
        examples=['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8155688/'],
    )


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIE
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class Handover(BaseModel):
    handoverType: HandoverType
    note: str | None = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class GeographicLocation(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Country or region of origin of the individual (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America).',
        examples=[
            {'id': 'GAZ:00002955', 'label': 'Slovenia'},
            {'id': 'GAZ:00002459', 'label': 'United States of America'},
            {'id': 'GAZ:00316959', 'label': 'Municipality of El Masnou'},
            {'id': 'GAZ:00000460', 'label': 'Eurasia'},
        ],
    )


class SeverityLevel(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Severity as applicable to phenotype or disease observed. Recommended are values from Human Phenotype Ontology (HP:0012824), e.g `mild`. The intensity or degree of a manifestation. Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012829', 'label': 'Profound'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
            {'id': 'HP:0012825', 'label': 'Mild'},
            {'id': 'HP:0012827', 'label': 'Borderline'},
        ],
    )


class Sex(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Sex of the individual. Recommended values from NCIT General Qualifier (NCIT:C27993): "unknown" (not assessed or not available) - NCIT:C17998; "female" - NCIT:C16576;  "male" - NCIT:C20197',
        examples=[
            {'id': 'NCIT:C16576', 'label': 'female'},
            {'id': 'NCIT:C20197', 'label': 'male'},
            {'id': 'NCIT:C1799', 'label': 'unknown'},
        ],
    )


class Unit(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='The kind of unit. Recommended from NCIT Unit of Category ontology term (NCIT:C42568) descendants',
        examples=[
            {'id': 'NCIT:C70575', 'label': 'Roentgen'},
            {'id': 'NCIT:C28252', 'label': 'Kilogram'},
            {'id': 'NCIT:C28253', 'label': 'Milligram'},
        ],
    )


class Pagination1(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class Exposure(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ageAtExposure: Age
    date: date_aliased | None = Field(
        None, description='Date of the exposure in ISO8601 format.'
    )
    duration: str = Field(
        ..., description='Exposure duration in ISO8601 format', examples=['P2Y6M1D']
    )
    exposureCode: OntologyTerm = Field(
        ...,
        description='Exposure ID. Recommended is a value from Environment Exposure Ontology.',
        examples=[
            {'id': 'CHEBI:46661', 'label': 'asbestos'},
            {'id': 'ENVO:21001217', 'label': 'X-ray radiation'},
        ],
    )
    unit: Unit = Field(
        ...,
        description='Unit of the exposure. Recommended from NCIT Unit of Category ontology term (NCIT:C42568) descendants.',
    )
    value: float | None = Field(None, description='Quantification of the exposure.')


class ReferenceRange(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    high: float = Field(..., description='Upper range end of normal', examples=[135])
    low: float = Field(..., description='Lower range end of normal', examples=[85])
    unit: Unit = Field(
        ...,
        description='The kind of unit.',
        examples=[{'id': 'NCIT:C49670', 'label': 'Millimeter of Mercury'}],
    )


class PedigreeMember(BaseModel):
    affected: bool = Field(
        ..., description='Is the individual affected by the disease in the pedigree?'
    )
    memberId: str = Field(
        ...,
        description="Identifier of the individual. The individual could be part of the same Beacon datasets or not, in which case the information here is meant to complete the pedigree. If the individual is also in the dataset use that Individual ID. If it is not the in the dataset, use a non-collading ID, e.g. concatenating the Pedigree ID with a local ID, similarly to the example 'Pedigree1001-m1'.",
        examples=['Pedigree1001-m1', 'Ind0012122'],
    )
    role: OntologyTerm = Field(
        ...,
        description='Pedigree role, defined as relationship to proband. Value from Family Member term (NCIT:C41256), e.g. "proband" (NCIT:C64435),"identical twin" (NCIT:C73429), "mother" (NCIT:C25189).',
        examples=[
            {'id': 'NCIT:C64435', 'label': 'Proband'},
            {'id': 'NCIT:C96580', 'label': 'Biological Mother'},
            {'id': 'NCIT:C96572', 'label': 'Biological Father'},
            {'id': 'NCIT:C165848', 'label': 'Identical Twin Brother'},
        ],
    )


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    evidenceCode: OntologyTerm = Field(
        ...,
        description='An ontology class that represents the evidence type',
        examples=[
            {
                'id': 'ECO:0006017',
                'label': 'author statement from published clinical study used in manual assertion',
            }
        ],
    )
    reference: ExternalReference | None = Field(
        None,
        description='Representation of the source of the evidence',
        examples=[
            {
                'id': 'PMID:30962759',
                'label': 'Recurrent Erythema Nodosum in a Child with a SHOC2 Gene Mutation',
            }
        ],
    )


class TimeElement(
    RootModel[Age | AgeRange | GestationalAge | Timestamp | TimeInterval | OntologyTerm]
):
    root: Age | AgeRange | GestationalAge | Timestamp | TimeInterval | OntologyTerm = (
        Field(
            ...,
            description='Definition of a wrapper for various time descriptors. This follows the\nPhenopackets structure https://github.com/phenopackets/phenopacket-schema/blob/v2/docs/time-element.rst',
            title='TimeElement',
        )
    )


class Ethnicity(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Ethnic background of the individual. Recommended is the use of a value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ]',
        examples=[
            {'id': 'NCIT:C42331', 'label': 'African'},
            {'id': 'NCIT:C41260', 'label': 'Asian'},
            {'id': 'NCIT:C126535', 'label': 'Australian'},
            {'id': 'NCIT:C43851', 'label': 'European'},
            {'id': 'NCIT:C77812', 'label': 'North American'},
            {'id': 'NCIT:C126531', 'label': 'Latin American'},
            {'id': 'NCIT:C104495', 'label': 'Other race'},
        ],
    )


class ListOfHandovers1(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Procedure(BaseModel):
    ageAtProcedure: TimeElement | None = Field(
        None, description='Compares to Phenopackets v2 `Procedure.performed`'
    )
    bodySite: OntologyTerm | None = Field(
        None,
        description='Specific body site where the procedure was performed. Recommended valuee from Uber-anatomy ontology (UBERON)',
        examples=[
            {'id': 'UBERON:0003403', 'label': 'Skin of forearm'},
            {'id': 'UBERON:0003214', 'label': 'mammary gland alveolus'},
        ],
    )
    dateOfProcedure: date_aliased | None = Field(
        None,
        description='Date of procedure, in ISO8601 format',
        examples=['2010-07-10'],
    )
    procedureCode: OntologyTerm = Field(
        ...,
        description="Clinical procedure performed with recommended values from Medical Action Ontology (MAXO) 'Medical action' term tree (MAXO:0000001). Compares to Phenopackets v2 `Procedure.code`",
        examples=[
            {'id': 'MAXO:0001175', 'label': 'liver transplantation'},
            {'id': 'MAXO:0000136', 'label': 'high-resolution microendoscopy'},
            {'id': 'OBI:0002654', 'label': 'needle biopsy'},
        ],
    )


class Quantity(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    referenceRange: ReferenceRange | None = Field(
        None, description='The normal range for the value', examples=[{}]
    )
    unit: Unit
    value: float = Field(..., description='The value of the quantity in the units')


class TypedQuantity(BaseModel):
    quantity: Quantity = Field(
        ...,
        description='Quantity denoting the outcome of the measurement',
        examples=[
            {
                'unit': {'id': 'NCIT:C49670', 'label': 'Millimeter of Mercury'},
                'value': 110,
            }
        ],
    )
    quantityType: OntologyTerm = Field(
        ...,
        description='OntologyClass to describe the type of the measurement. Renamed compared to GA4GH Phenopackets v2 `ComplexValue.TypedQuantity.type`',
        examples=[{'id': 'NCIT:C25298', 'label': 'Systolic Blood Pressure'}],
    )


class PhenotypicFeature(BaseModel):
    evidence: Evidence | None = Field(
        None,
        description='The evidence for an assertion of the observation of a type. RECOMMENDED.',
    )
    excluded: bool | None = Field(
        False,
        description='Flag to indicate whether the phenotypic feature was observed or not. Default is ‘false’, in other words the phenotype was observed. Therefore it is only used in cases where the phenotype was looked for but found to be absent. More formally, this modifier indicates the logical negation of the OntologyClass used in the `featureType` field. CAUTION: It is imperative to check this field for correct interpretation of the phenotype! Source: Phenopackets v2',
    )
    featureType: OntologyTerm = Field(
        ...,
        description='Term denoting the phenotypic feature, preferably using a value from Human Phenotype Ontology (HPO)',
        examples=[
            {'id': 'HP:0000002', 'label': 'Abnormality of body height'},
            {'id': 'HP:0002006', 'label': 'Facial cleft'},
            {'id': 'HP:0012469', 'label': 'Infantile spasms'},
        ],
    )
    modifiers: list[OntologyTerm] | None = Field(
        None,
        description='This subontology is designed to provide terms to characterize and specify the phenotypic abnormalities defined in the Phenotypic abnormality subontology, with respect to severity, laterality, age of onset, and other aspects. Example use here would be one or more terms from HPO Clinical Modifier (HP:0012823). Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0032500', 'label': 'Exacerbated by tobacco use'},
            {'id': 'HP:4000053', 'label': 'Displaced fracture'},
        ],
    )
    notes: str | None = Field(
        None,
        description='Unstructured text to describe additional properties of this phenotypic feature.',
        examples=['Some free text'],
    )
    onset: TimeElement | None = Field(
        None, description='Age or time at which the feature was first observed.'
    )
    resolution: TimeElement | None = Field(
        None, description='Age or time at which the feature resolved or abated.'
    )
    severity: SeverityLevel | None = Field(
        None,
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
        ],
    )


class DoseInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interval: TimeInterval = Field(
        ...,
        description='The specific interval over which the dosage was administered in the indicated quantity.',
        examples=[{'end': '1967-11-18T12:00:00+01', 'start': '1967-11-11T07:30:00+01'}],
    )
    quantity: Quantity
    scheduleFrequency: OntologyTerm = Field(
        ...,
        description='How often doses are administered per day (or other indicated duration)',
        examples=[{'id': 'NCIT:C64496', 'label': 'Twice Daily'}],
    )


class Disease(BaseModel):
    ageOfOnset: TimeElement | None = Field(
        None,
        examples=[
            {'id': 'NCIT:C49685', 'label': 'Adult 18-65 Years Old'},
            {'iso8601duration': 'P32Y6M1D'},
            {'end': {'iso8601duration': 'P59Y'}, 'start': {'iso8601duration': 'P18Y'}},
            {'iso8601duration': 'P2M4D'},
        ],
    )
    diseaseCode: OntologyTerm = Field(
        ...,
        description='Disease identifier. Value from disease ontologies such as HPO, OMIM, Orphanet, MONDO, e.g. lactose intolerance (HP:0004789, ICD10CM:E73). Provenance: GA4GH Phenopackets v2 `Disease.term`',
        examples=[
            {'id': 'HP:0004789', 'label': 'lactose intolerance'},
            {'id': 'ICD10CM:E73', 'label': 'lactose intolerance'},
            {'id': 'OMIM:164400', 'label': 'Spinocerebellar ataxia 1'},
        ],
    )
    familyHistory: bool | None = Field(
        None,
        description='Boolean indicating determined or self-reported presence of family history of the disease.',
        examples=[True],
    )
    notes: str | None = Field(
        None,
        description='Unstructured text to describe additional properties of this disease instance.',
        examples=['Some free text'],
    )
    severity: SeverityLevel | None = Field(
        None,
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
        ],
    )
    stage: OntologyTerm | None = Field(
        None,
        description='Ontology term from Ontology for General Medical Science (OGMS), e.g. acute onset (OGMS:0000119). Provenance: GA4GH Phenopackets v2 `Disease.disease_stage`',
        examples=[
            {'id': 'OGMS:0000119', 'label': 'acute onset'},
            {'id': 'OGMS:0000117', 'label': 'asymptomatic'},
            {'id': 'OGMS:0000106', 'label': 'remission'},
        ],
    )


class Value(RootModel[Quantity | OntologyTerm]):
    root: Quantity | OntologyTerm = Field(
        ...,
        description='Definition of a value class. Provenance: GA4GH Phenopackets v2 `Value`',
        title='Value',
    )


class ComplexValue(BaseModel):
    typedQuantities: list[TypedQuantity] = Field(
        ...,
        description='List of quantities required to fully describe the complex value',
    )


class Pedigree(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    disease: Disease
    id: str = Field(..., description='Pedigree identifier.', examples=['Pedigree1001'])
    members: list[PedigreeMember] = Field(
        ...,
        description='List of members of the pedigree. If the current pedigree definition is attached to the proband, it contains the whole list of pedigree members, including the proband. If the definition is attached to an individual different than the proband, it only contains two entries: one that describes that member, e.g. the proband mother or father, and one that points to the proband.',
        min_length=1,
    )
    numSubjects: int | None = Field(
        None, description='Total number of subjects in pedigree.', examples=[10]
    )


class Treatment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ageAtOnset: Age | None = None
    cumulativeDose: Quantity | None = None
    doseIntervals: list[DoseInterval] | None = None
    routeOfAdministration: OntologyTerm | None = Field(
        None,
        description='Route of treatment. Value from NCIT Route of Administration tree (NCIT:C38114).',
        examples=[
            {'id': 'NCIT:C38304', 'label': 'Topical'},
            {'id': 'NCIT:C78373', 'label': 'Dietary'},
        ],
    )
    treatmentCode: OntologyTerm = Field(
        ...,
        description='Code of treatment. Value from NCIT or any relevant ontology. Compares to `agent` in Phenopackets v2',
        examples=[
            {'id': 'NCIT:C287', 'label': 'Aspirin'},
            {'id': 'NCIT:C62078', 'label': 'Tamoxifen'},
        ],
    )


class Measurement(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    assayCode: OntologyTerm = Field(
        ...,
        description='Class that describes the assay used to produce the measurement. Renamed compared to GA4GH Phenopackets v2 `Measurement.assay`',
        examples=[{'id': 'LOINC:26515-7', 'label': 'Platelets [#/volume] in Blood'}],
    )
    date: date_aliased | None = Field(
        None,
        description='Date of measurement. Addition compared to Phenopackets model.',
    )
    measurementValue: Value | ComplexValue = Field(
        ..., description='The result of the measurement'
    )
    notes: str | None = Field(
        None,
        description='Unstructured text to describe this measurement. Addition compared to Phenopackets model.',
        examples=['Some free text'],
    )
    observationMoment: TimeElement | None = Field(
        None,
        description='Moment in time at which measurement was performed. RECOMMENDED. Renamed compared to GA4GH Phenopackets v2 `Measurement.time_observed`',
        examples=[{'age': {'iso8601duration': 'P53Y8M'}}],
    )
    procedure: Procedure | None = Field(
        None,
        description='Clinical procedure performed to acquire the sample used for the measurement',
        examples=[
            {'code': {'id': 'NCIT:C5189', 'label': 'Radical Cystoprostatectomy'}}
        ],
    )


class Individuals(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    diseases: list[Disease] | None = Field(
        None,
        description='List of disease(s) been diagnosed to the individual, defined by disease ontology ID(s), age of onset, stage and the presence of family history.',
    )
    ethnicity: Ethnicity | None = Field(
        None,
        description='Ethnic background of the individual. Value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ] ',
    )
    exposures: list[Exposure] | None = None
    geographicOrigin: GeographicLocation | None = Field(
        None,
        description="Individual's country or region of origin (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America).",
    )
    id: str = Field(
        ..., description='Individual identifier (internal ID).', examples=['P0001']
    )
    info: Info | None = None
    interventionsOrProcedures: list[Procedure] | None = None
    karyotypicSex: KaryotypicSex | None = Field(
        'UNKNOWN_KARYOTYPE',
        description='The chromosomal sex of an individual represented from a selection of options.',
    )
    measurements: list[Measurement] | None = None
    pedigrees: list[Pedigree] | None = None
    phenotypicFeatures: list[PhenotypicFeature] | None = None
    sex: Sex = Field(
        ...,
        description='Sex of the individual. Value from NCIT General Qualifier `NCIT:C27993`:    * `unknown`: not assessed or not availablel `NCIT:C17998` * `female`: `NCIT:C16576` * `male`: `NCIT:C20197`',
    )
    treatments: list[Treatment] | None = None
