# generated by datamodel-codegen:
#   filename:  defaultSchema.json
#   timestamp: 2026-07-27T12:22:51+00:00

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr
from validators.separated import ConfigModel

class LibraryLayout(Enum):
    PAIRED = 'PAIRED'
    SINGLE = 'SINGLE'


class Info(BaseModel):
    pass


class CURIE(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: str | None = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CountAdjustedToItem(RootModel[conint(ge=1) | str]):
    root: conint(ge=1) | str


class CountAdjustedTo(RootModel[list[CountAdjustedToItem]]):
    root: list[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[list[str]]):
    root: list[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        10,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        True,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class SchemasPerEntity(BaseModel):
    entityType: str | None = Field(None, examples=['Individual'])
    schema_: str | None = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        0,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class TestMode(RootModel[bool]):
    root: bool = Field(
        False,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIE
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class ListOfSchemas(RootModel[list[SchemasPerEntity]]):
    root: list[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class Pagination(BaseModel):
    currentPage: PageToken | None = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Limit | None = Field(10, validate_default=True)
    nextPage: PageToken | None = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: PageToken | None = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Skip | None = Field(0, validate_default=True)


class Runs(ConfigModel):
    model_config = ConfigDict(
        extra='allow',
    )
    biosampleId: str = Field(
        ...,
        description='Reference to the biosample ID.',
        examples=['008dafdd-a3d1-4801-8c0a-8714e2b58e48'],
    )
    id: str = Field(..., description='Run ID.', examples=['SRR10903401'])
    individualId: str | None = Field(
        None, description='Reference to the individual ID.', examples=['TCGA-AO-A0JJ']
    )
    info: Info | None = None
    libraryLayout: LibraryLayout | None = Field(
        None,
        description='Ontology value for the library layout e.g "PAIRED", "SINGLE" #todo add Ontology name?',
    )
    librarySelection: str | None = Field(
        None,
        description='Selection method for library preparation, e.g "RANDOM", "RT-PCR"',
        examples=['RANDOM', 'RT-PCR'],
    )
    librarySource: OntologyTerm | None = Field(
        None,
        description='Ontology value for the source of the sequencing or hybridization library, e.g "genomic source", "transcriptomic source"',
        examples=[
            {'id': 'GENEPIO:0001966', 'label': 'genomic source'},
            {'id': 'GENEPIO:0001965', 'label': 'metagenomic source'},
        ],
    )
    libraryStrategy: str | None = Field(
        None, description='Library strategy, e.g. "WGS"', examples=['WGS']
    )
    platform: str | None = Field(
        None,
        description='General platform technology label. It SHOULD be a subset of the platformModel and used only for query convenience, e.g. "return everything sequenced with Illimuna", where the specific model is not relevant',
        examples=['Illumina', 'Oxford Nanopore', 'Affymetrix'],
    )
    platformModel: OntologyTerm | None = Field(
        None,
        description='Ontology value for experimental platform or methodology used. For sequencing platforms the use of "OBI:0400103 - DNA sequencer" is suggested.',
        examples=[
            {'id': 'OBI:0002048', 'label': 'Illumina HiSeq 3000'},
            {'id': 'OBI:0002750', 'label': 'Oxford Nanopore MinION'},
            {'id': 'EFO:0010938', 'label': 'large-insert clone DNA microarray'},
        ],
    )
    runDate: date = Field(
        ...,
        description='Date at which the experiment was performed.',
        examples=['2021-10-18'],
    )


class Handover(BaseModel):
    handoverType: HandoverType
    note: str | None = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers(RootModel[list[Handover]]):
    root: list[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )
