# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/EGA-archive/EUCAIM-Schema/refs/heads/main/CollectionsMetadata.json
#   timestamp: 2026-07-30T20:48:15+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


from validators.config import ConfigModel


class Age(RootModel[Any]):
    root: Any


class AgeRange(BaseModel):
    min: Age
    max: Age


class Collections(ConfigModel):
    name: str = Field(
        ..., description='Name of the dataset', examples=['Dataset with synthetic data']
    )
    id: str = Field(
        ..., description='Unique identifier of the dataset', examples=['ds01010101']
    )
    description: str = Field(
        ...,
        description='Description of the dataset',
        examples=[
            'This dataset provides examples of the actual data in this Beacon instance.'
        ],
    )
    subjectsCount: conint(ge=0)
    studiesCount: conint(ge=0)
    ageRange: AgeRange
    modalities: list[str]
    bodyParts: list[str]
    gender: list[str]
