# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/EGA-archive/EUCAIM-Schema/refs/heads/main/PatientsMetadata.json
#   timestamp: 2026-07-30T16:55:25+00:00

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr

from validators.config import ConfigModel


class Sex(RootModel[Any]):
    root: Any


class Age(RootModel[Any]):
    root: Any


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HER2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HistologicGraceGleasonScore(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HistologicGradeISUP(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class TumorBIRADSAssesment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class TumorPIRADSAssesment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )
    label: str | None = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class TumorsMetadata(BaseModel):
    tumorId: str = Field(
        ...,
        description='A unique identifier for the Tumor. This field was not in the original EUCAIM Federated Query metadata.',
        examples=['X123456-T01'],
    )
    ER: OntologyTerm | None = Field(
        None,
        description='Estrogen receptor Ag [Presence] in Breast cancer specimen by Immune stain',
        examples=[
            {'id': 'EUCAIM:COM1001310', 'label': 'Positive'},
            {'id': 'EUCAIM:COM1001332', 'label': 'Negative'},
        ],
    )
    PR: OntologyTerm | None = Field(
        None,
        description='Progesterone receptor Ag [Presence] in Breast cancer specimen by Immune stain',
        examples=[
            {'id': 'EUCAIM:COM1001310', 'label': 'Positive'},
            {'id': 'EUCAIM:COM1001332', 'label': 'Negative'},
        ],
    )
    PSA: float | None = Field(
        None,
        description='Prostate specific Ag [Mass/Volume] in Serum or Plasma',
        examples=[4.5],
    )
    HER2_1: HER2 | None = Field(
        None,
        alias='HER2',
        description='HER2 [Presence] in Breast cancer specimen by Immune stain',
        examples=[
            {'id': 'EUCAIM:COM1002257', 'label': '0'},
            {'id': 'EUCAIM:COM1001877', 'label': '1+'},
            {'id': 'EUCAIM:COM1001879', 'label': '2+'},
            {'id': 'EUCAIM:COM1001882', 'label': '3+'},
        ],
        title='Ontology Term',
    )
    KI67: float | None = Field(
        None,
        description='Cells.Ki-67 nuclear Ag/100 cells in Breast cancer specimen by Immune stain',
        examples=[2.4],
    )
    cancerStageCMCategory: OntologyTerm | None = Field(
        None,
        description='The cancer stage according to the cM category system.',
        examples=[
            {'id': 'EUCAIM:COM1001860', 'label': 'cM0'},
            {'id': 'EUCAIM:COM1000246', 'label': 'cM1'},
            {'id': 'EUCAIM:COM1000258', 'label': 'cM1a'},
            {'id': 'EUCAIM:COM1000271', 'label': 'cM1b'},
            {'id': 'EUCAIM:COM1001876', 'label': 'cM1c'},
        ],
    )
    cancerStagePMCategory: OntologyTerm | None = Field(
        None,
        description='The cancer stage according to the pM category system.',
        examples=[
            {'id': 'EUCAIM:COM1001845', 'label': 'pM0'},
            {'id': 'EUCAIM:COM1000531', 'label': 'pM1'},
            {'id': 'EUCAIM:COM1000558', 'label': 'pM1a'},
            {'id': 'EUCAIM:COM1000586', 'label': 'pM1b'},
            {'id': 'EUCAIM:COM1000615', 'label': 'pM1c'},
        ],
    )
    histologicGraceGleasonScore: HistologicGraceGleasonScore | None = Field(
        None,
        description='The Gleason scoring system for malignant neoplasm of prostate',
        examples=[
            {'id': 'EUCAIM:CLIN1025818', 'label': 'Gleason grade score 2 out of 10'},
            {'id': 'EUCAIM:CLIN1025912', 'label': 'Gleason score 3 out of 10'},
            {'id': 'EUCAIM:CLIN1026007', 'label': 'Gleason score 4 out of 10'},
        ],
        title='Ontology Term',
    )
    histologicGradeISUP: HistologicGradeISUP | None = Field(
        None,
        description='The International Society of Urological Pathology (ISUP) grading system for malignant neoplasm of prostate',
        examples=[
            {
                'id': 'EUCAIM:COM1001362',
                'label': 'International Society of Pathology histologic group 1',
            },
            {
                'id': 'EUCAIM:COM1001365',
                'label': 'International Society of Pathology histologic group 2',
            },
            {
                'id': 'EUCAIM:COM1001367',
                'label': 'International Society of Pathology histologic group 3',
            },
        ],
        title='Ontology Term',
    )
    tumorBIRADSAssesment: TumorBIRADSAssesment | None = Field(
        None,
        description='Breast Imaging-Reporting and Data System (BI-RADS) assessment categories for breast tumors',
        examples=[
            {'id': 'EUCAIM:IMG1005470', 'label': 'BI-RADS 0'},
            {'id': 'EUCAIM:IMG1005469', 'label': 'BI-RADS 1'},
            {'id': 'EUCAIM:IMG1005468', 'label': 'BI-RADS 2'},
            {'id': 'EUCAIM:IMG1005466', 'label': 'BI-RADS 3'},
        ],
        title='Ontology Term',
    )
    tumorPIRADSAssesment: TumorPIRADSAssesment | None = Field(
        None,
        description='Prostate Imaging-Reporting and Data System (PI-RADS) assessment categories for prostate tumors',
        examples=[
            {'id': 'EUCAIM:IMG1005487', 'label': 'PI-RADS 1'},
            {'id': 'EUCAIM:IMG1005486', 'label': 'PI-RADS 2'},
            {'id': 'EUCAIM:IMG1005485', 'label': 'PI-RADS 3'},
            {'id': 'EUCAIM:IMG1005484', 'label': 'PI-RADS 4'},
        ],
        title='Ontology Term',
    )


class ImageModality(RootModel[Any]):
    root: Any


class BodyPart(RootModel[Any]):
    root: Any


class DiseasesMetadata(BaseModel):
    diseaseId: str = Field(
        ...,
        description='Unique identifier for the diagnostic/disease. This field was not in the original EUCAIM Federated Query metadata.',
        examples=['X123456-D01'],
    )
    ageAtDiagnosis: Age = Field(
        ...,
        description='Age of the patient at the time the tumor or lesion was confirmed.',
        examples=[45.6],
    )
    diagnosis: OntologyTerm = Field(
        ...,
        description='Diagnosis of the disease.',
        examples=[
            {'id': 'EUCAIM:CLIN1000075', 'label': 'Malignant neoplasm of prostate'},
            {'id': 'EUCAIM:CLIN1000060', 'label': 'Malignant neoplasm of breast'},
            {'id': 'EUCAIM:CLIN1000057', 'label': 'Malignant neoplasm of colon'},
            {'id': 'EUCAIM:CLIN1000185', 'label': 'Malignant neoplasm of rectum'},
        ],
    )
    yearOfDiagnosis: int | None = Field(
        None,
        description='Date when the tumor was histologically confirmed or confirmed by imaging.',
        examples=['2022'],
    )
    dateOfFirstTreatment: AwareDatetime | None = Field(
        None,
        description='Date and time when the first treatment occurred, in ISO 8601 date-time format.',
        examples=['2024-03-01T10:30:00Z'],
    )
    pathologyConfirmation: OntologyTerm | None = Field(
        None,
        description='Method used to confirm pathology (e.g., histological biopsy or imaging for specific cases).',
        examples=[
            {'id': 'EUCAIM:CLIN1001712', 'label': 'Biopsy'},
            {'id': 'EUCAIM:CLIN1004598', 'label': 'Excision'},
        ],
    )
    pathology: list[OntologyTerm] | None = Field(
        None,
        description='Histology and histological subtype of the lesion (ICD-O-3 if available).',
        examples=[
            [
                {'id': 'EUCAIM:CLIN1047138', 'label': 'Adenocarcinoma'},
                {'id': 'EUCAIM:CLIN1063544', 'label': 'Papillary carcinoma'},
            ]
        ],
    )
    imagingProcedureProtocol: OntologyTerm | None = Field(
        None,
        description='Specific protocol applied to obtain the radiology diagnostic image.',
        examples=[
            [
                {'id': 'EUCAIM:IMG1000076', 'label': 'CT of thorax with contrast'},
                {'id': 'EUCAIM:IMG1000078', 'label': 'CT of breast'},
            ]
        ],
    )
    treatment: list[OntologyTerm] | None = Field(
        None,
        description='Type of treatment received by the patient.',
        examples=[
            [
                {'id': 'EUCAIM:CLIN1024528', 'label': 'Chemotherapy'},
                {'id': 'EUCAIM:COM1001099', 'label': 'Surgery'},
            ]
        ],
    )
    tumorMetadata: TumorsMetadata | None = Field(
        None, description='Additional metadata related to the tumor or lesion.'
    )


class ImageStudiesMetadata(BaseModel):
    imageStudyId: str = Field(
        ...,
        description='Unique identifier for the image. This field was not in the original EUCAIM Federated Query metadata.',
        examples=['X123456-IMG01'],
    )
    disease: DiseasesMetadata = Field(
        ..., description='Disease information associated with the image.'
    )
    imageModality: ImageModality = Field(
        ...,
        description='Modality of the imaging study (DICOM tag 0008,0060), controlled vocabulary',
        examples=[
            {'id': 'EUCAIM:IMG1000026', 'label': 'Computed tomography'},
            {'id': 'EUCAIM:IMG1000030', 'label': 'Mammography'},
        ],
    )
    imageBodyPart: BodyPart = Field(
        ...,
        description='Anatomical area imaged (DICOM tag 0018,0015), controlled vocabulary',
        examples=[
            {'id': 'EUCAIM:BP1000067', 'label': 'Chest'},
            {'id': 'EUCAIM:BP1000220', 'label': 'Arm'},
        ],
    )
    imageManufacturer: OntologyTerm = Field(
        ...,
        description='Device manufacturer (DICOM tag 0008,0070), controlled vocabulary',
        examples=[
            {'id': 'EUCAIM:IMG1000047', 'label': 'General Electric'},
            {'id': 'EUCAIM:IMG1000044', 'label': 'Siemens'},
        ],
    )
    dateOfImageAcquisition: AwareDatetime = Field(
        ...,
        description='Acquisition date of the image (DICOM tag 0008,0022), in ISO 8601 date-time format (e.g. YYYY-MM-DDThh:mm:ssZ).',
        examples=['2000-01-01T00:00:00Z'],
    )


class Patients(ConfigModel):
    patientId: str = Field(
        ...,
        description='A unique identifier for the patient. Should match the Patient ID DICOM tag (0010,0020) and anonymization processes.',
        examples=['X123456'],
    )
    sex: Sex = Field(
        ...,
        description='Biological sex at birth.',
        examples=[
            {'id': 'EUCAIM:COM1001370', 'label': 'Female'},
            {'id': 'EUCAIM:COM1001366', 'label': 'Male'},
            {'id': 'EUCAIM:COM1001288', 'label': 'Unspecified'},
        ],
    )

    imageStudy: list[ImageStudiesMetadata] = Field(
        ..., description='Imaging study information associated with the patient.'
    )
